import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";

import Logout from "./logout";
import Link from "next/link";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log(session?.user);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && (
            <>
              <p>{session?.user?.username}</p>
              <p>{session?.user?.accessToken}</p>
              <Logout></Logout>
            </>
          )}
          {!session && <Link href={"/api/auth/login"}>Login</Link>}
        </nav>
        {children}
      </body>
    </html>
  );
}
